### ISSUE TITLE
pkg-config: not found

### ISSUE THREAD

**Issue by abhijeetps** [gr2m/glitch-deploy#10]
I tried running `npx glitch-deploy` on Ubuntu 1804 on Windows 10, it's showing this error.

```
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aps120797/.npm/_npx/932/lib/node_modules/glitch-deploy/node_modules/keytar
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
After this, it started downloading Chromium r515411.

Here's Ubuntu's configuration: 
`$ lsb_release -a`
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

```
I am not sure what the error is, but I think it's worth submitting an issue. 😃

**Comment by gr2m** [comment]
I couldn’t reproduce your issue, however I run into https://github.com/glitch-tools/glitch-deploy/issues/9
