### ISSUE TITLE
Evaluation failed: TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by BrotherSymeon** [gr2m/glitch-deploy#16]
They must have changed something on the sight again. I downloaded the 1.1.6 version of glitch-deploy and this is what happened when I tried to deploy

[StJohnSales] npm i glitch-deploy -g                                                                                                                                         8:09:34  ☁  master ☀
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/home/innocent/.nvm/versions/node/v10.15.3/bin/glitch-deploy -> /home/innocent/.nvm/versions/node/v10.15.3/lib/node_modules/glitch-deploy/bin/glitch-deploy.js

> keytar@4.13.0 install /home/innocent/.nvm/versions/node/v10.15.3/lib/node_modules/glitch-deploy/node_modules/keytar
> prebuild-install || node-gyp rebuild

> puppeteer@0.13.0 install /home/innocent/.nvm/versions/node/v10.15.3/lib/node_modules/glitch-deploy/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/innocent/.nvm/versions/node/v10.15.3/lib/node_modules/glitch-deploy/node_modules/puppeteer/.local-chromium/linux-515411
+ glitch-deploy@1.1.6
added 140 packages from 91 contributors in 52.377s
[StJohnSales] DEBUG=glitch-deploy* glitch-deploy                                                                                                                             8:10:54  ☁  master ☀
  glitch-deploy glitch.com loaded +0ms
Error: Evaluation failed: TypeError: Cannot read property 'click' of undefined
    at <anonymous>:3:63
    at ExecutionContext.evaluateHandle (/home/innocent/.nvm/versions/node/v10.15.3/lib/node_modules/glitch-deploy/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by mym0404** [comment]
![image](https://user-images.githubusercontent.com/33388801/86103118-50974200-baf7-11ea-8d69-20ed67a38478.png)

me too
