### ISSUE TITLE
Issue with GitHub username

### ISSUE THREAD

**Issue by agonzalez0515** [gr2m/glitch-deploy#2]
Using node version 8.4. Ran `DEBUG=glitch-deploy* npx glitch-deploy` and got the following error after entering my GitHub username:

```
DEBUG=glitch-deploy* npx glitch-deploy
  glitch-deploy glitch.com loaded +0ms
  glitch-deploy Login with GitHub +3ms
? What is your GitHub username? agonzalez0515
TypeError: Cannot read property 'then' of undefined
    at Object.when (/Users/angelicagonzalez/rails-girls/bot/node_modules/glitch-deploy/lib/get-github-credentials.js:24:59)
    at /Users/angelicagonzalez/rails-girls/bot/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /Users/angelicagonzalez/rails-girls/bot/node_modules/run-async/index.js:24:19
    at /Users/angelicagonzalez/rails-girls/bot/node_modules/inquirer/lib/ui/prompt.js:106:30
    at tryCatcher (/Users/angelicagonzalez/rails-girls/bot/node_modules/rx-lite/rx.lite.js:67:31)
    at Defer.subscribeCore (/Users/angelicagonzalez/rails-girls/bot/node_modules/rx-lite/rx.lite.js:2159:37)
    at Defer.tryCatcher (/Users/angelicagonzalez/rails-girls/bot/node_modules/rx-lite/rx.lite.js:67:31)
    at setDisposable (/Users/angelicagonzalez/rails-girls/bot/node_modules/rx-lite/rx.lite.js:1849:46)
    at Defer.Rx.ObservableBase.ObservableBase._subscribe (/Users/angelicagonzalez/rails-girls/bot/node_modules/rx-lite/rx.lite.js:1864:9)
```

**Comment by gr2m** [comment]
fixed via #4
